@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Feb 24 14:27:55 +0500 2026
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim top_rf_alu_tb_behav -key {Behavioral:sim_1:Functional:top_rf_alu_tb} -tclbatch top_rf_alu_tb.tcl -view C:/Users/sm09751/Downloads/CAlab5+6+7/CAlab5+6+7/CAlab5/top_rf_alu_tb_behav.wcfg -log simulate.log"
call xsim  top_rf_alu_tb_behav -key {Behavioral:sim_1:Functional:top_rf_alu_tb} -tclbatch top_rf_alu_tb.tcl -view C:/Users/sm09751/Downloads/CAlab5+6+7/CAlab5+6+7/CAlab5/top_rf_alu_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
